name: tec_shop
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  cloud_firestore: ^4.4.4
  shared_preferences: ^2.0.18
  form_field_validator: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  iconsax: ^0.0.8
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  http: ^0.13.5
  flutter_localization: ^0.1.10
  flutter_svg: ^2.0.3
  restart_app: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locale/ar/
    - assets/locale/en/
    - assets/themes/light/
    - assets/themes/dark/
    - assets/icons/
